### ISSUE TITLE
during CI build we see these errors

### ISSUE THREAD

**Issue by veeramarni** [jonnynabors/docusaurus2-dotenv#1]
When enabled this plugin uses the `.env` file we get this error in our Jenkin builds. It works locally but it fails in the Jenkin. 

Any idea what it could be due to?
```
yarn run v1.22.10

$ yarn workspace clockbook-website-v1 docusaurus graphql-to-doc -f && yarn workspace clockbook-website-v1 build

$ docusaurus graphql-to-doc -f

The docs plugin option homePageId=clockbook is deprecated. To make a doc the "home", prefer frontmatter: "slug: /"

Documentation successfully generated in "docs/api" with base URL "api".

723 pages generated in 15.553s from schema "https://covid-graph-graphql.now.sh/".

Remember to update your Docusaurus site's sidebars with "docs/api/sidebar-schema.js".

$ docusaurus build



[en] Creating an optimized production build...

The docs plugin option homePageId=clockbook is deprecated. To make a doc the "home", prefer frontmatter: "slug: /"

warn Duplicate routes found!

Attempting to create page at /blog, but a page already exists at this route

This could lead to non-deterministic routing behavior

Failed to load ./config/development/.env.

Failed to load ./config/development/.env.

[info] [webpackbar] Compiling Client

[info] [webpackbar] Compiling Server

[success] [webpackbar] Client: Compiled successfully in 2.71m

[success] [webpackbar] Server: Compiled with some errors in 2.75m





main:95655

		"false" = namespaces;

		^^^^^^^



SyntaxError: Invalid left-hand side in assignment

(undefined) main:95655

		"false" = namespaces;

		^^^^^^^



SyntaxError: Invalid left-hand side in assignment

    at new Script (vm.js:88:7)

    at module.exports (/home/jenkins/workspace/clock-tik/node_modules/eval/eval.js:73:18)

    at /home/jenkins/workspace/clock-tik/node_modules/@endiliey/static-site-generator-webpack-plugin/index.js:42:22

    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/jenkins/workspace/clock-tik/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)

    at AsyncSeriesHook.lazyCompileHook (/home/jenkins/workspace/clock-tik/node_modules/tapable/lib/Hook.js:154:20)

    at /home/jenkins/workspace/clock-tik/node_modules/webpack/lib/Compilation.js:1414:32

    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/jenkins/workspace/clock-tik/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)

    at AsyncSeriesHook.lazyCompileHook (/home/jenkins/workspace/clock-tik/node_modules/tapable/lib/Hook.js:154:20)

    at /home/jenkins/workspace/clock-tik/node_modules/webpack/lib/Compilation.js:1409:36

    at eval (eval at create (/home/jenkins/workspace/clock-tik/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)

    at /home/jenkins/workspace/clock-tik/node_modules/copy-webpack-plugin/dist/index.js:598:9

error building locale=en

Error: Failed to compile with errors.

    at /home/jenkins/workspace/clock-tik/node_modules/@docusaurus/core/lib/webpack/utils.js:195:24

    at finalCallback (/home/jenkins/workspace/clock-tik/node_modules/webpack/lib/MultiCompiler.js:254:12)

    at /home/jenkins/workspace/clock-tik/node_modules/webpack/lib/MultiCompiler.js:277:6

    at done (/home/jenkins/workspace/clock-tik/node_modules/neo-async/async.js:2931:13)

    at runCompilers (/home/jenkins/workspace/clock-tik/node_modules/webpack/lib/MultiCompiler.js:181:48)

    at /home/jenkins/workspace/clock-tik/node_modules/webpack/lib/MultiCompiler.js:188:7

    at /home/jenkins/workspace/clock-tik/node_modules/webpack/lib/MultiCompiler.js:270:7

    at finalCallback (/home/jenkins/workspace/clock-tik/node_modules/webpack/lib/Compiler.js:257:39)

    at /home/jenkins/workspace/clock-tik/node_modules/webpack/lib/Compiler.js:273:13

    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/jenkins/workspace/clock-tik/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:40:1)

    at AsyncSeriesHook.lazyCompileHook (/home/jenkins/workspace/clock-tik/node_modules/tapable/lib/Hook.js:154:20)

    at onCompiled (/home/jenkins/workspace/clock-tik/node_modules/webpack/lib/Compiler.js:271:21)

    at /home/jenkins/workspace/clock-tik/node_modules/webpack/lib/Compiler.js:681:15

    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/jenkins/workspace/clock-tik/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)

    at AsyncSeriesHook.lazyCompileHook (/home/jenkins/workspace/clock-tik/node_modules/tapable/lib/Hook.js:154:20)

    at /home/jenkins/workspace/clock-tik/node_modules/webpack/lib/Compiler.js:678:31

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

error Command failed.

Exit code: 1

Command: /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs/bin/node

Arguments: /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs/lib/node_modules/yarn/lib/cli.js build

Directory: /home/jenkins/workspace/clock-tik/websites/website-v1

Output:



info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

script returned exit code 1
```

**Comment by veeramarni** [comment]
related to https://github.com/visionmedia/debug/issues/467
